name: vision_career_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3
  screen_protector: ^1.5.1
  flutter:
    sdk: flutter
  http: ^1.2.1
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#08111F"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/data/vision_career_phase1_phase2_master_dataset_rebuilt.json
    - assets/images/icon.png
    - assets/icons/
    - assets/json/
    - assets/json/it_subject_graph.xlsx

